const SCREEN_ROUTER_APP = {
  PRODUCT: 'PRODUCT',
  NOTIFICATION: 'NOTIFICATION',
  CART: 'CART',
  PRODUCT_FLASH_SALE: 'PRODUCT_FLASH_SALE',
  PRODUCT_SELLING: 'PRODUCT_SELLING',
  HOME: 'HOME',
  ORDER: 'ORDER',
  USER: 'USER',
  CREATE_POST: 'CREATE_POST',
  LOCATION: 'LOCATION',
}

const MAIN_TAB = {
  HOME: 'HOME',
  LOCATION: 'LOCATION',
  CREATE_POST: 'CREATE_POST',
  USER: 'USER',
  NOTIFICATION: 'NOTIFICATION',
}

const API_STATUS = {
  SUCCESS: 200,
  CREATED: 201,
  NOTFOUND: 404,
  BAD_REQUEST: 400,
  SERVER: 500,
  UNAUTHORIZED: 401,
  CONFLICT: 409,
  FORBIDDEN: 403,
  BAD_GATEWAY: 502,
  NOT_EXISTED: 405,
}

const SCREEN_ROUTER_APP_ADMIN = {
  PRODUCT: 'PRODUCT',
  NOTIFICATION: 'NOTIFICATION',
  CART: 'CART',
}

const SCREEN_ROUTER_AUTH = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  LOGIN_STEP_2: 'LOGIN_STEP_2',
  REGISTER: 'REGISTER',
  FORGET_PASSWORD: 'FORGOT_PASSWORD',
  FORGET_PASSWORD_STEP_2: 'FORGET_PASSWORD_STEP_2',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  OTP: 'OTP',
}

const SCREEN_ROUTER = {
  SPLASH: 'SPLASH',
  AUTH: 'AUTH',
  MAIN: 'MAIN',
}

export const ROOT_STACK = {
  MAIN_APP: 'MAIN_APP',
}

export const APP_SLICE = {
  SWITCH: 'switchNavigatorReducer',
}

const DEFAULT_PARAMS = {
  PAGE: 1,
  LIMIT: 24,
}

const PHONE_REGEX =
  /^(0|\+84)(\s|\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\d)(\s|\.)?(\d{3})(\s|\.)?(\d{3})$/

const EMAIL_REGEX =
  /^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i
const PASSWORD_REGEX = /^.{8,25}$/
export {
  DEFAULT_PARAMS,
  SCREEN_ROUTER,
  SCREEN_ROUTER_APP,
  SCREEN_ROUTER_APP_ADMIN,
  SCREEN_ROUTER_AUTH,
  API_STATUS,
  PHONE_REGEX,
  EMAIL_REGEX,
  PASSWORD_REGEX,
  MAIN_TAB,
}
