const images = {
  ic_arrow_down: require('./images/ic_arrow_down.png'),
  ic_arrow_right: require('./images/ic_arrow_right.png'),
  ic_arrow_right_circle: require('./images/ic_arrow_right_circle.png'),
  ic_back: require('./images/ic_back.png'),
  ic_backgroud: require('./images/ic_backgroud.png'),
  ic_cart: require('./images/ic_cart.png'),
  ic_cart_blue: require('./images/ic_cart_blue.png'),
  ic_cart_focus: require('./images/ic_cart_focus.png'),
  ic_chat_blue: require('./images/ic_chat_blue.png'),
  ic_checked: require('./images/ic_checked.png'),
  ic_chevron_right: require('./images/ic_chevron_right.png'),
  ic_example_category: require('./images/ic_example_category.png'),
  ic_eye: require('./images/ic_eye.png'),
  ic_eye_hide: require('./images/ic_eye_hide.png'),
  ic_home: require('./images/ic_home.png'),
  ic_home_focus: require('./images/ic_home_focus.png'),
  ic_logo: require('./images/ic_logo.png'),
  ic_product: require('./images/ic_product.png'),
  ic_profile: require('./images/ic_profile.png'),
  ic_profile_focus: require('./images/ic_profile_focus.png'),
  ic_search: require('./images/ic_search.png'),
  ic_unchecked: require('./images/ic_unchecked.png'),
  img_back: require('./images/img_back.png'),
  img_construction_example: require('./images/img_construction_example.png'),
  img_design_example: require('./images/img_design_example.png'),
  img_error: require('./images/img_error.png'),
  img_example_product: require('./images/img_example_product.png'),
  img_hand_over_example: require('./images/img_hand_over_example.png'),
  img_logo: require('./images/img_logo.png'),
  img_product_no_complete: require('./images/img_product_no_complete.png'),
  img_project_completed: require('./images/img_project_completed.png'),
  img_project_home: require('./images/img_project_home.png'),
  img_vietbuiltding_banner: require('./images/img_vietbuiltding_banner.png'),
}
export default images
