import I18n from '@app/i18n/i18n'
function strings() {
  return {
    lao: I18n.t('lao', { defaultValue: '' }),
    cancel: I18n.t('cancel', { defaultValue: '' }),
    confirm: I18n.t('confirm', { defaultValue: '' }),
    notification: I18n.t('notification', { defaultValue: '' }),
    re_login: I18n.t('re_login', { defaultValue: '' }),
    try_again: I18n.t('try_again', { defaultValue: '' }),
    account: I18n.t('account', { defaultValue: '' }),
    home: I18n.t('home', { defaultValue: '' }),
    product: I18n.t('product', { defaultValue: '' }),
    order: I18n.t('order', { defaultValue: '' }),
    login: I18n.t('login', { defaultValue: '' }),
    please_login: I18n.t('please_login', { defaultValue: '' }),
    cart: I18n.t('cart', { defaultValue: '' }),
    register: I18n.t('register', { defaultValue: '' }),
    full_name: I18n.t('full_name', { defaultValue: '' }),
    input_full_name: I18n.t('input_full_name', { defaultValue: '' }),
    phone: I18n.t('phone', { defaultValue: '' }),
    input_phone: I18n.t('input_phone', { defaultValue: '' }),
    email: I18n.t('email', { defaultValue: '' }),
    input_email: I18n.t('input_email', { defaultValue: '' }),
    password: I18n.t('password', { defaultValue: '' }),
    input_password: I18n.t('input_password', { defaultValue: '' }),
    confirm_password: I18n.t('confirm_password', { defaultValue: '' }),
    input_confirm_password: I18n.t('input_confirm_password', {
      defaultValue: '',
    }),
    referral_code: I18n.t('referral_code', { defaultValue: '' }),
    input_referral_code: I18n.t('input_referral_code', { defaultValue: '' }),
    validatePhone: I18n.t('validatePhone', { defaultValue: '' }),
    validateEmail: I18n.t('validateEmail', { defaultValue: '' }),
    validateName: I18n.t('validateName', { defaultValue: '' }),
    validatePassword: I18n.t('validatePassword', { defaultValue: '' }),
    you_are_business: I18n.t('you_are_business', { defaultValue: '' }),
    company_name: I18n.t('company_name', { defaultValue: '' }),
    input_company_name: I18n.t('input_company_name', { defaultValue: '' }),
    tax_code: I18n.t('tax_code', { defaultValue: '' }),
    input_tax_code: I18n.t('input_tax_code', { defaultValue: '' }),
    address_tax_code: I18n.t('address_tax_code', { defaultValue: '' }),
    address_input_tax_code: I18n.t('address_input_tax_code', {
      defaultValue: '',
    }),
    forgot_password: I18n.t('forgot_password', { defaultValue: '' }),
    note_input_phone: I18n.t('note_input_phone', { defaultValue: '' }),
    note_otp: I18n.t('note_otp', { defaultValue: '' }),
    send: I18n.t('send', { defaultValue: '' }),
    expire: I18n.t('expire', { defaultValue: '' }),
    send_back_otp: I18n.t('send_back_otp', { defaultValue: '' }),
    change_password: I18n.t('change_password', { defaultValue: '' }),
    login_with_your_account: I18n.t('login_with_your_account', {
      defaultValue: '',
    }),
    remember_account: I18n.t('remember_account', { defaultValue: '' }),
    you_have_not_an_account: I18n.t('you_have_not_an_account', {
      defaultValue: '',
    }),
    next: I18n.t('next', { defaultValue: '' }),
    phone_blank: I18n.t('phone_blank', { defaultValue: '' }),
    note_phone: I18n.t('note_phone', { defaultValue: '' }),
    password_note: I18n.t('password_note', { defaultValue: '' }),
    note_email: I18n.t('note_email', { defaultValue: '' }),
    email_blank: I18n.t('email_blank', { defaultValue: '' }),
    note_pass: I18n.t('note_pass', { defaultValue: '' }),
    password_blank: I18n.t('password_blank', { defaultValue: '' }),
    question_email: I18n.t('question_email', { defaultValue: '' }),
    send_back: I18n.t('send_back', { defaultValue: '' }),
    note_change_pass: I18n.t('note_change_pass', { defaultValue: '' }),
    confirm_password_not_success: I18n.t('confirm_password_not_success', {
      defaultValue: '',
    }),
    address: I18n.t('address', { defaultValue: '' }),
    name_blank: I18n.t('name_blank', { defaultValue: '' }),
    address_blank: I18n.t('address_blank', { defaultValue: '' }),
    please_update_avatar: I18n.t('please_update_avatar', { defaultValue: '' }),
    category: I18n.t('category', { defaultValue: '' }),
    edit_user_info: I18n.t('edit_user_info', { defaultValue: '' }),
    support_list: I18n.t('support_list', { defaultValue: '' }),
    contact: I18n.t('contact', { defaultValue: '' }),
    terms: I18n.t('terms', { defaultValue: '' }),
    logout: I18n.t('logout', { defaultValue: '' }),
    not_update: I18n.t('not_update', { defaultValue: '' }),
    see_more: I18n.t('see_more', { defaultValue: '' }),
    support: I18n.t('support', { defaultValue: '' }),
    number_support: I18n.t('number_support', { defaultValue: '' }),
    create_post: I18n.t('create_post', { defaultValue: '' }),
    image: I18n.t('image', { defaultValue: '' }),
    video: I18n.t('video', { defaultValue: '' }),
    location: I18n.t('location', { defaultValue: '' }),
    offer: I18n.t('offer', { defaultValue: '' }),
    post: I18n.t('post', { defaultValue: '' }),
    update_account: I18n.t('update_account', { defaultValue: '' }),
    re_password_fail: I18n.t('re_password_fail', { defaultValue: '' }),
    placeholder_current_password: I18n.t('placeholder_current_password', {
      defaultValue: '',
    }),
    placeholder_new_pass: I18n.t('placeholder_new_pass', { defaultValue: '' }),
    cmt: I18n.t('cmt', { defaultValue: '' }),
    date_of_birthday: I18n.t('date_of_birthday', { defaultValue: '' }),
    sex: I18n.t('sex', { defaultValue: '' }),
    choose: I18n.t('choose', { defaultValue: '' }),
    save: I18n.t('save', { defaultValue: '' }),
    back: I18n.t('back', { defaultValue: '' }),
    recipient: I18n.t('recipient', { defaultValue: '' }),
    input_address: I18n.t('input_address', { defaultValue: '' }),
    information_supporters: I18n.t('information_supporters', {
      defaultValue: '',
    }),
    subject: I18n.t('subject', { defaultValue: '' }),
    group_type: I18n.t('group_type', { defaultValue: '' }),
    need: I18n.t('need', { defaultValue: '' }),
    male: I18n.t('male', { defaultValue: '' }),
    female: I18n.t('female', { defaultValue: '' }),
    personal: I18n.t('personal', { defaultValue: '' }),
    community: I18n.t('community', { defaultValue: '' }),
    note_image: I18n.t('note_image', { defaultValue: '' }),
    note_video: I18n.t('note_video', { defaultValue: '' }),
    address_detail: I18n.t('address_detail', { defaultValue: '' }),
    select_address_map: I18n.t('select_address_map', { defaultValue: '' }),
    suggest_address: I18n.t('suggest_address', { defaultValue: '' }),
    permission_location: I18n.t('permission_location', { defaultValue: '' }),
    list_post: I18n.t('list_post', { defaultValue: '' }),
    supported_list: I18n.t('supported_list', { defaultValue: '' }),
    manage_list_post: I18n.t('manage_list_post', { defaultValue: '' }),
    manage_list_support: I18n.t('manage_list_support', { defaultValue: '' }),
  }
}
export default strings
